### ISSUE TITLE
Error in ArcanistESLintLinter when more than one file is linted

### ISSUE THREAD

**Issue by ericlucit** [freelancer/flarc#2]
There is a bug in /src/lint/linter/ArcanistESLintLinter.php in the return statement for parseLinterOutput function

This causes the following error when linting more than 1 file and at least 1 of the files contains no lint errors

How to reproduce

1.  Update fileA.js with something that will trigger eslint 
2.  Update fileB.js but this file has no lint problems

run `arc lint fileA.js fileB.js` and you will get the exception below.

```
 Exception
Some linters failed:
    - CommandException: Command failed with error #1!

```

The cause is because the return statement is inside of the foreach instead of outside of it

I have attached a simple diff below that resolves the issue

```diff
diff --git a/src/lint/linter/ArcanistESLintLinter.php b/src/lint/linter/ArcanistESLintLinter.php
index da63528..7b23d44 100644
--- a/src/lint/linter/ArcanistESLintLinter.php
+++ b/src/lint/linter/ArcanistESLintLinter.php
@@ -192,9 +192,10 @@ final class ArcanistESLintLinter extends ArcanistBatchExternalLinter {

         $results[] = $result;
       }
-
-      return $results;
     }
+
+    return $results;
+
   }

 }

```

**Comment by solarnz** [comment]
This should be fixed with 6fc9cea638719d9acc1a43ea1dbcae41ae58abd7
